# module du helios launcher
name: Launcher Build
on:
  push:
    branches:
      - main
      - release/*


jobs:
  release:
    #runs-on: ${{ matrix.os }}
    name: Release
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm i
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: npm run build
        shell: bash

      - name: Upload Release Assets (Linux, Darwin, Windows)
        # You may pin to the exact commit or the version.
        # uses: wzshiming/action-upload-release-assets@0c2e3232b7d78049e062fcf756847e159b24298a
        uses: wzshiming/action-upload-release-assets@v1

